#JOB & STAGE name shold not have any spaces
#default azure runs stages parallely, to make it sequential we should write condition

trigger:
- main

pool: azure

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'



