#JOB & STAGE name shold not have any spaces
#default azure runs stages parallely, to make it sequential we should write condition

trigger:
- main

pool: Default

steps:
- script: npm install
  displayName: 'install nodejs dependencies'

- script: docker build -t cart .
  displayName: 'build docker image'

- script:
    aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u3t4a1d0
  displayName: 'upload an artifact 1 '
- script:
    docker tag cart:latest public.ecr.aws/u3t4a1d0/cart:latest
  displayName: 'upload an artifact 2 '
- script:
    docker push public.ecr.aws/u3t4a1d0/cart:latest
  displayName: 'upload an artifact 3 '




